<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU2F4xhT\Kematjaya_SecurityAnnotationBundle_Test_AppKernelTestTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU2F4xhT/Kematjaya_SecurityAnnotationBundle_Test_AppKernelTestTestDebugContainer.php') {
    touch(__DIR__.'/ContainerU2F4xhT.legacy');

    return;
}

if (!\class_exists(Kematjaya_SecurityAnnotationBundle_Test_AppKernelTestTestDebugContainer::class, false)) {
    \class_alias(\ContainerU2F4xhT\Kematjaya_SecurityAnnotationBundle_Test_AppKernelTestTestDebugContainer::class, Kematjaya_SecurityAnnotationBundle_Test_AppKernelTestTestDebugContainer::class, false);
}

return new \ContainerU2F4xhT\Kematjaya_SecurityAnnotationBundle_Test_AppKernelTestTestDebugContainer([
    'container.build_hash' => 'U2F4xhT',
    'container.build_id' => 'f87874d0',
    'container.build_time' => 1607670747,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU2F4xhT');
